Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 120

Layout/LineLength:
  Max: 400

Layout/ClassLength:
  Max: 400

Layout/BlockLength:
  Max: 50

Layout/CyclomaticComplexityLength:
  Max: 15

Metrics/AbcSize:
  Enabled: false
